CREATE TABLE "escalations" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"type_id" integer,
	"class_scope" text NOT NULL,
	"trigger_notes" text NOT NULL,
	"blue_loot_isk" bigint,
	"isk_per_ehp_min" integer,
	"isk_per_ehp_max" integer,
	"shield_hp" bigint,
	"shield_res_em" integer,
	"shield_res_exp" integer,
	"shield_res_kin" integer,
	"shield_res_therm" integer,
	"armor_hp" bigint,
	"armor_res_em" integer,
	"armor_res_exp" integer,
	"armor_res_kin" integer,
	"armor_res_therm" integer,
	"structure_hp" bigint,
	"ehp_min" bigint,
	"ehp_max" bigint,
	"dps" integer,
	"sig" integer,
	"speed" integer,
	"distance" integer,
	"velocity" integer,
	"scram" integer,
	"web" integer,
	"neut" integer,
	"rrep" integer,
	CONSTRAINT "escalations_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "sleeper_archetypes" (
	"type_id" integer PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"blue_loot_isk" bigint,
	"turret_dps" integer,
	"turret_alpha" integer,
	"missile_dps" integer,
	"missile_alpha" integer,
	"total_dps" integer,
	"total_alpha" integer,
	"shield_hp" bigint,
	"shield_res_em" integer,
	"shield_res_exp" integer,
	"shield_res_kin" integer,
	"shield_res_therm" integer,
	"armor_hp" bigint,
	"armor_res_em" integer,
	"armor_res_exp" integer,
	"armor_res_kin" integer,
	"armor_res_therm" integer,
	"structure_hp" bigint,
	"ehp" bigint,
	"sig_radius" integer,
	"max_velocity" integer,
	"orbit_distance" integer,
	"orbit_velocity" integer,
	"scram" integer,
	"web" integer,
	"neut_amount" integer,
	"neut_duration" integer,
	"neut_count" integer,
	"rrep_amount" integer,
	"rrep_duration" integer,
	"rrep_count" integer
);
