// Generated from `.fallowrc.json` by `pnpm generate:architecture-map`.
// Do not edit by hand: a drift test byte-compares this file against a fresh run,
// so an edit here fails the suite instead of shipping a map the rules disagree with.

/** Zone-level dependency graph derived from the `boundaries` block of `.fallowrc.json`. */
export const architectureMap = {
  nodes: [
    { id: 'ui', label: 'ui', layer: 0, kind: 'zone' },
    { id: 'platform__auth', label: 'platform/auth', layer: 5, kind: 'zone' },
    { id: 'platform__owner_sync', label: 'platform/owner-sync', layer: 3, kind: 'zone' },
    { id: 'platform__esi', label: 'platform/esi', layer: 2, kind: 'zone' },
    { id: 'platform__search', label: 'platform/search', layer: 0, kind: 'zone' },
    { id: 'platform__purge', label: 'platform/purge', layer: 0, kind: 'zone' },
    { id: 'platform__page_settings', label: 'platform/page-settings', layer: 2, kind: 'zone' },
    { id: 'composition', label: 'composition', layer: 8, kind: 'zone' },
    { id: 'components_composition', label: 'components-composition', layer: 9, kind: 'zone' },
    { id: 'features', label: 'features', layer: 7, kind: 'group' },
    { id: 'data', label: 'data', layer: 4, kind: 'group' },
    { id: 'lib', label: 'lib', layer: 1, kind: 'zone' },
    { id: 'components', label: 'components', layer: 6, kind: 'zone' },
    { id: 'api', label: 'api', layer: 9, kind: 'zone' },
    { id: 'app', label: 'app', layer: 10, kind: 'zone' },
    { id: 'scripts', label: 'scripts', layer: 9, kind: 'zone' },
    { id: 'transport', label: 'transport', layer: 2, kind: 'zone' },
    { id: 'db', label: 'db', layer: 2, kind: 'zone' },
    { id: 'config', label: 'config', layer: 0, kind: 'zone' },
    { id: 'esi_datasets', label: 'esi-datasets', layer: 9, kind: 'zone' },
    { id: 'convex', label: 'convex', layer: 6, kind: 'zone' },
    { id: 'runtime', label: 'runtime', layer: 8, kind: 'zone' },
    { id: 'data__eve_data', label: 'data/eve-data', layer: 0, kind: 'reference-core' },
  ],
  edges: [
    { from: 'app', to: 'components_composition', kind: 'allow' },
    { from: 'app', to: 'composition', kind: 'allow' },
    { from: 'app', to: 'components', kind: 'allow' },
    { from: 'app', to: 'ui', kind: 'allow' },
    { from: 'app', to: 'features', kind: 'allow' },
    { from: 'app', to: 'platform__auth', kind: 'allow' },
    { from: 'app', to: 'platform__esi', kind: 'allow' },
    { from: 'app', to: 'platform__page_settings', kind: 'allow' },
    { from: 'app', to: 'data', kind: 'allow' },
    { from: 'app', to: 'transport', kind: 'allow' },
    { from: 'app', to: 'lib', kind: 'allow' },
    { from: 'app', to: 'config', kind: 'allow' },
    { from: 'api', to: 'transport', kind: 'allow' },
    { from: 'api', to: 'composition', kind: 'allow' },
    { from: 'api', to: 'features', kind: 'allow' },
    { from: 'api', to: 'platform__auth', kind: 'allow' },
    { from: 'api', to: 'platform__esi', kind: 'allow' },
    { from: 'api', to: 'data', kind: 'allow' },
    { from: 'api', to: 'db', kind: 'allow' },
    { from: 'api', to: 'lib', kind: 'allow' },
    { from: 'api', to: 'config', kind: 'allow' },
    { from: 'scripts', to: 'composition', kind: 'allow' },
    { from: 'scripts', to: 'platform__auth', kind: 'allow' },
    { from: 'scripts', to: 'data', kind: 'allow' },
    { from: 'scripts', to: 'db', kind: 'allow' },
    { from: 'scripts', to: 'lib', kind: 'allow' },
    { from: 'runtime', to: 'transport', kind: 'allow' },
    { from: 'runtime', to: 'features', kind: 'allow' },
    { from: 'runtime', to: 'data', kind: 'allow' },
    { from: 'runtime', to: 'lib', kind: 'allow' },
    { from: 'runtime', to: 'config', kind: 'allow' },
    { from: 'composition', to: 'features', kind: 'allow' },
    { from: 'composition', to: 'platform__auth', kind: 'allow' },
    { from: 'composition', to: 'platform__owner_sync', kind: 'allow' },
    { from: 'composition', to: 'platform__esi', kind: 'allow' },
    { from: 'composition', to: 'platform__search', kind: 'allow' },
    { from: 'composition', to: 'platform__purge', kind: 'allow' },
    { from: 'composition', to: 'platform__page_settings', kind: 'allow' },
    { from: 'composition', to: 'data', kind: 'allow' },
    { from: 'composition', to: 'transport', kind: 'allow' },
    { from: 'composition', to: 'db', kind: 'allow' },
    { from: 'composition', to: 'lib', kind: 'allow' },
    { from: 'composition', to: 'config', kind: 'allow' },
    { from: 'components_composition', to: 'composition', kind: 'allow' },
    { from: 'components_composition', to: 'components', kind: 'allow' },
    { from: 'components_composition', to: 'ui', kind: 'allow' },
    { from: 'components_composition', to: 'features', kind: 'allow' },
    { from: 'components_composition', to: 'platform__auth', kind: 'allow' },
    { from: 'components_composition', to: 'platform__search', kind: 'allow' },
    { from: 'components_composition', to: 'platform__page_settings', kind: 'allow' },
    { from: 'components_composition', to: 'data', kind: 'allow' },
    { from: 'components_composition', to: 'transport', kind: 'allow' },
    { from: 'components_composition', to: 'lib', kind: 'allow' },
    { from: 'components_composition', to: 'config', kind: 'allow' },
    { from: 'features', to: 'platform__auth', kind: 'allow' },
    { from: 'features', to: 'platform__owner_sync', kind: 'allow' },
    { from: 'features', to: 'platform__search', kind: 'allow' },
    { from: 'features', to: 'platform__purge', kind: 'allow' },
    { from: 'features', to: 'platform__page_settings', kind: 'allow' },
    { from: 'features', to: 'data', kind: 'allow' },
    { from: 'features', to: 'transport', kind: 'allow' },
    { from: 'features', to: 'db', kind: 'allow' },
    { from: 'features', to: 'lib', kind: 'allow' },
    { from: 'features', to: 'config', kind: 'allow' },
    { from: 'features', to: 'ui', kind: 'allow' },
    { from: 'features', to: 'components', kind: 'allow' },
    { from: 'components', to: 'ui', kind: 'allow' },
    { from: 'components', to: 'platform__auth', kind: 'allow' },
    { from: 'components', to: 'platform__search', kind: 'allow' },
    { from: 'components', to: 'platform__page_settings', kind: 'allow' },
    { from: 'components', to: 'data', kind: 'allow' },
    { from: 'components', to: 'transport', kind: 'allow' },
    { from: 'components', to: 'lib', kind: 'allow' },
    { from: 'data', to: 'platform__esi', kind: 'allow' },
    { from: 'data', to: 'platform__owner_sync', kind: 'allow' },
    { from: 'data', to: 'platform__search', kind: 'allow' },
    { from: 'data', to: 'platform__purge', kind: 'allow' },
    { from: 'data', to: 'transport', kind: 'allow' },
    { from: 'data', to: 'db', kind: 'allow' },
    { from: 'data', to: 'lib', kind: 'allow' },
    { from: 'data', to: 'config', kind: 'allow' },
    { from: 'platform__auth', to: 'platform__esi', kind: 'allow' },
    { from: 'platform__auth', to: 'platform__purge', kind: 'allow' },
    { from: 'platform__auth', to: 'data', kind: 'allow' },
    { from: 'platform__auth', to: 'transport', kind: 'allow' },
    { from: 'platform__auth', to: 'db', kind: 'allow' },
    { from: 'platform__auth', to: 'lib', kind: 'allow' },
    { from: 'platform__auth', to: 'config', kind: 'allow' },
    { from: 'platform__owner_sync', to: 'platform__esi', kind: 'allow' },
    { from: 'platform__esi', to: 'lib', kind: 'allow' },
    { from: 'platform__esi', to: 'config', kind: 'allow' },
    { from: 'platform__page_settings', to: 'lib', kind: 'allow' },
    { from: 'transport', to: 'lib', kind: 'allow' },
    { from: 'db', to: 'lib', kind: 'allow' },
    { from: 'db', to: 'config', kind: 'allow' },
    { from: 'lib', to: 'config', kind: 'allow' },
    { from: 'convex', to: 'platform__esi', kind: 'allow' },
    { from: 'convex', to: 'platform__auth', kind: 'allow' },
    { from: 'convex', to: 'data', kind: 'allow' },
    { from: 'convex', to: 'lib', kind: 'allow' },
    { from: 'esi_datasets', to: 'composition', kind: 'allow' },
    { from: 'esi_datasets', to: 'db', kind: 'allow' },
    { from: 'esi_datasets', to: 'data', kind: 'allow' },
    { from: 'esi_datasets', to: 'features', kind: 'allow' },
    { from: 'esi_datasets', to: 'platform__auth', kind: 'allow' },
    { from: 'esi_datasets', to: 'platform__purge', kind: 'allow' },
    { from: 'esi_datasets', to: 'lib', kind: 'allow' },
    { from: 'data', to: 'data__eve_data', kind: 'exception' },
    { from: 'api', to: 'app', kind: 'carve-out' },
  ],
} as const;
